#SPDX-License-Identifier: MIT-0
# Aquí se declaran las tareas que ejecutará Ansible para 
# el rol de vm
---
- name: Actualizando listado de repositorios...
  become: yes
  ansible.builtin.apt:
    update_cache: yes

- name: Instalando Podman...
  become: yes
  ansible.builtin.apt:
    name: 
      - podman
      - openssl
      - python3-passlib
    state: present

# Se Creará un usuario con autenticación básica para acceso a la página web
- name: Creando usuario basico...
  become: yes
  ansible.builtin.user:
    name: "{{ usuario_basico }}"
    password: "{{ password_basico | password_hash('sha512') }}"

- name: Accediendo a ACR...
  become: yes
  containers.podman.podman_login:
    registry: "{{ acr_url }}"
    username: "{{ acr_user }}"
    password: "{{ acr_password }}"

- name: Descargando imagen desde ACR...
  become: yes
  containers.podman.podman_image:
    name: "{{ acr_url }}/{{ app_name }}"
    tag: "{{ tag_imagen }}"
    pull: true

# Es necesario crear un directorio en /opt para poder crear un volumen
# de cara a customizar el contenedor de nginx con la página web personalizada,
# certificado autofirmado y método de autenticación
- name: Creando directorio de volumen appdata...
  become: yes
  ansible.builtin.file:
    path: "{{ nginx_volume_appdata }}"
    state: directory
    mode: '0755'

# Sobre el diretorio raíz anterior, vamos a montar subdirectorios para dividir
# cada servicio personalizado.
- name: Creando directorio de volumen nginx...
  become: yes
  ansible.builtin.file:
    path: "{{ nginx_volume_parent }}"
    state: directory
    mode: '0755'

# Sobre el diretorio raíz anterior, vamos a montar subdirectorios para dividir
# cada servicio personalizado. Aquí se añadirán los certificados autofirmados.

- name: Creando directorio de volumen ssl...
  become: yes
  ansible.builtin.file:
    path: "{{ nginx_volume_ssl }}"
    state: directory
    mode: '0755'

# Sobre el diretorio raíz anterior, vamos a montar subdirectorios para dividir
# cada servicio personalizado. Aquí se añadirá la configuración de redireccionamiento
# al puerto 443 y reglas de autenticación
- name: Creando directorio de volumen conf...
  become: yes
  ansible.builtin.file:
    path: "{{ nginx_volume_conf }}"
    state: directory
    mode: '0755'

# Generamos la clave privada de la CA
- name: Generando clave privada de la CA...
  become: yes
  community.crypto.openssl_privatekey:
    path: "{{ nginx_volume_ssl }}/{{ nginx_ca_key }}"
    size: 2048

- name: Generando CSR de la CA...
  become: yes
  community.crypto.openssl_csr:
    path: "{{ nginx_volume_ssl }}/{{ nginx_ca_csr }}"
    privatekey_path: "{{ nginx_volume_ssl }}/{{ nginx_ca_key }}"
    common_name: "{{ ca_common_name}}"
    organization_name: "{{ ca_organization_name }}"
    country_name: "{{ ca_country_name }}"
    use_common_name_for_san: false
    basic_constraints:
      - "{{ ca_basic_constraints }}"
    basic_constraints_critical: true
    key_usage:
      - keyCertSign
      - cRLSign
    key_usage_critical: true

# Generamos el certificado raíz de la CA autofirmado
- name: Generando certificado raíz de la CA...
  become: yes
  community.crypto.x509_certificate:
    path: "{{ nginx_volume_ssl }}/{{ nginx_ca_cert }}"
    privatekey_path: "{{ nginx_volume_ssl }}/{{ nginx_ca_key }}"
    csr_path: "{{ nginx_volume_ssl }}/{{ nginx_ca_csr }}"
    provider: selfsigned
    selfsigned_digest: "{{ cert_selfsigned_digest }}"
    selfsigned_not_after: "{{ cert_selfsigned_not_after }}"
    selfsigned_not_before: "{{ cert_selfsigned_not_before }}"

# Aquí generamos la clave privada para el certificado autofirmado
- name: Generando clave privada SSL...
  become: yes
  community.crypto.openssl_privatekey:
    path: "{{ nginx_volume_ssl }}/{{ nginx_cert_key }}"
    size: 2048

# Aquí generamos el certificado CSR a partir de la clave privada. Aquí se almacenan
# los datos de la entidad certificadora, origen, autor, organización... 
# Tamién se configura con un identificados SAN, los navegadores actuales necesitan este identificador
# para permitir acceder a ese dominio/IP autofirmado
- name: Generando CSR con SAN...
  become: yes
  community.crypto.openssl_csr:
    path: "{{ nginx_volume_ssl }}/{{ nginx_cert_csr }}"
    privatekey_path: "{{ nginx_volume_ssl }}/{{ nginx_cert_key }}"
    common_name: "{{ ansible_host }}"
    organization_name: "{{ OrganizationNameCert }}"
    subject_alt_name:
      - "IP:{{ ansible_host }}"
    extended_key_usage:
      - serverAuth
    extended_key_usage_critical: false

# Aquí se genera el certificado autofirmado en base a los 
# ficheros previos generados
- name: Generando certificado autofirmado x.509 firmado por la CA...
  become: yes
  community.crypto.x509_certificate:
    path: "{{ nginx_volume_ssl }}/{{ nginx_cert_crt }}"
    privatekey_path: "{{ nginx_volume_ssl }}/{{ nginx_cert_key }}"
    csr_path: "{{ nginx_volume_ssl }}/{{ nginx_cert_csr }}"
    provider: ownca
    ownca_path: "{{ nginx_volume_ssl }}/{{ nginx_ca_cert }}"
    ownca_privatekey_path: "{{ nginx_volume_ssl }}/{{ nginx_ca_key }}"
    selfsigned_digest: "{{ cert_selfsigned_digest }}"

# Descargamos el certificado CA a la máquina de control para importarlo en el navegador
# almacenamos el certificado en /tmp para importarlo en el navegador y posteriormente
# se eliminará a mano de ese directorio o en el próximo reinicio.
- name: Descargando certificado CA a la máquina de control...
  become: yes
  ansible.builtin.fetch:
    src: "{{ nginx_volume_ssl }}/{{ nginx_ca_cert }}"
    dest: "/tmp/ca.crt"
    flat: yes

# Generamos un fichero de configuración para el método de autenticación
# básica con usuario y clave del usuario creado previamente.
- name: Creando fichero htpasswd...
  become: yes
  community.general.htpasswd:
    path: "{{ nginx_volume_conf }}/.htpasswd"
    name: "{{ usuario_basico }}"
    password: "{{ password_basico }}"
    mode: '0644'

# Copiamos la configuración de autenticación básica al contenedor.
- name: Copiando configuración de nginx...
  become: yes
  ansible.builtin.template:
    src: "{{ nginx_template_config }}"
    dest: "{{ nginx_volume_conf }}/{{ nginx_destination_config }}"
    mode: '0644'

# Copiamos fichero index.html de la web personalizada
- name: Copiando página web personalizada...
  become: yes
  ansible.builtin.copy:
    src: "{{ web_index_template }}"
    dest: "{{ nginx_volume_appdata }}/{{ web_index_destination }}"
    mode: '0644'

# Iniciamos el contenedor con la imagen seleccionada y la apertura
# de puertos y asignación de volúmenes para los datos/configuraciones
# personalizadas aplicadas.
- name: Arrancando contenedor con volumen...
  become: yes
  containers.podman.podman_container:
    name: app
    image: "{{ acr_url }}/{{ app_name }}:{{ tag_imagen }}"
    state: started
    ports:
      - "{{ nginx_port_host }}:{{ nginx_port_container }}"
      - "{{ nginx_ssl_port_host }}:{{ nginx_ssl_port_container }}"
    volumes:
      - "{{ nginx_volume_appdata }}:/usr/share/nginx/html:ro"
      - "{{ nginx_volume_ssl }}:/etc/nginx/ssl:ro"
      - "{{ nginx_volume_conf }}/{{ nginx_destination_config }}:/etc/nginx/conf.d/default.conf:ro"
      - "{{ nginx_volume_conf }}/.htpasswd:/etc/nginx/.htpasswd:ro"
    recreate: yes

# Prueba de reinicio manual e inicial tras construcción para verificar que los datos siguen ahí
# y la página web funciona.
- name: Reiniciando servicio del contenedor...
  become: yes
  containers.podman.podman_container:
    name: app
    image: "{{ app_name }}:{{ tag_imagen }}"
    state: started
    restart: true
    restart_policy: "no"
    ports:
        - "{{ nginx_port_host }}:{{ nginx_port_container }}"
