#SPDX-License-Identifier: MIT-0
# tasks file for roles/vm
---
- name: Actualizando listado de repositorios...
  become: yes
  ansible.builtin.apt:
    update_cache: yes

- name: Instalando Podman...
  become: yes
  ansible.builtin.apt:
    name: podman
    state: present

- name: Creando usuario basico...
  become: yes
  ansible.builtin.user:
    name: "{{ usuario_basico }}"
    password: "{{ password_basico | password_hash('sha512') }}"

- name: Accediendo a ACR...
  become: yes
  containers.podman.podman_login:
    registry: "{{ acr_url }}"
    username: "{{ acr_user }}"
    password: "{{ acr_password }}"

- name: Descargando imagen desde ACR...
  become: yes
  containers.podman.podman_image:
    name: "{{ acr_url }}/{{ app_name }}"
    tag: "{{ tag_imagen }}"
    pull: true

- name: Creando directorio de volumen...
  become: yes
  ansible.builtin.file:
    path: /opt/appdata
    state: directory
    owner: "{{ usuario_basico }}"
    mode: '0755'

- name: Arrancando contenedor con volumen...
  become: yes
  containers.podman.podman_container:
    name: app
    image: "{{ acr_url }}/{{ app_name }}:{{ tag_imagen }}"
    state: started
    ports:
      - "{{ nginx_port_host }}:{{ nginx_port_container }}"
    volumes:
      - "/opt/{{ nginx_volume }}:/data"
    recreate: yes

- name: Reiniciando servicio del contenedor...
  become: yes
  containers.podman.podman_container:
    name: app
    image: "{{ app_name }}:{{ tag_imagen }}"
    state: started
    restart: true
    restart_policy: "no"
    ports:
        - "{{ nginx_port_host }}:{{ nginx_port_container }}"
