---
app_name: "nginx"
tag_imagen: "casopractico2"
nginx_port_host: 8086
nginx_port_container: 80
nginx_ssl_port_host: 443
nginx_ssl_port_container: 443
nginx_volume_appdata: "/opt/appdata"
nginx_volume_parent: "/opt/nginx"
nginx_volume_ssl: "/opt/nginx/ssl"
nginx_volume_conf: "/opt/nginx/conf"
nginx_cert_crt: "nginx.crt"
nginx_cert_key: "nginx.key"
nginx_cert_csr: "nginx.csr"
OrganizationNameCert: "UNIR"
nginx_template_config: "nginx.conf.j2"
nginx_destination_config: "nginx.conf"
web_index_template: "index.html"
web_index_destination: "index.html"

nginx_volume: "appdata"
imagenes:
  - src: "docker.io/library/nginx:latest"
    dst: "nginx"
  - src: "docker.io/bitnami/redis:latest"
    dst: "redis"
  - src: "docker.io/suhuruli/azure-vote-front:latest"
    dst: "azure-vote-front"

############################################
# Azure / AKS
############################################
resource_group: cp2ResourceGroup
aks_name: tf-aks-casopractico2
kubeconfig_dir: "{{ ansible_env.HOME }}/.kube"
kubeconfig_path: "{{ ansible_env.HOME }}/.kube/config"

############################################
# Aplicación AKS
############################################
app_namespace: onfp-casopractico2

app:
  frontend:
    name: frontend
    image: "{{ acr_url }}/azure-vote-front:casopractico2"
    replicas: 1
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 250m
      memory: 256Mi
    port: 80
    external_port: 8080
    redis_env: backend
  backend:
    name: backend
    image: "{{ acr_url }}/redis:casopractico2"
    replicas: 1
    port: 6379
    port_name: redis
    pv: redis-data
    pv_size: 1Gi
    storage_class: managed-csi
    volumepath: /bitnami/redis/data
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 250m
      memory: 256Mi