# SPDX-License-Identifier: MIT-0
# En este fichero declaramos las tareas que ejecutará ansible para el role
# del aks
---

# Creo el directorio `.kube` dónde se almacenarán las credenciales
- name: Creando directorio .kube si no existe...
  ansible.builtin.file:
    path: "{{ kubeconfig_dir }}"
    state: directory
    mode: '0700'

# Obtengo las credenciales del clúster AKS y las guardo en un fichero temporal 
# para su uso posterior con el módulo kubernetes.core.k8s
- name: Obteniendo credenciales del clúster AKS...
  azure.azcollection.azure_rm_akscredentials_info:
    resource_group: "{{ resource_group }}"
    cluster_name: "{{ aks_name }}"
    show_admin_credentials: true
  register: aks_credentials

# Guardando kubeconfig en fichero temporal con permisos restrictivos para su uso posterior con el módulo kubernetes.core.k8s
- name: Guardando kubeconfig en fichero temporal...
  ansible.builtin.copy:
    content: "{{ aks_credentials.cluster_credentials[0].value }}"
    dest: "{{ kubeconfig_path }}"
    mode: '0600'

# Creo un namespace específico para la aplicación a desplegar
- name: Creando namespace...
  kubernetes.core.k8s:
    name: "{{ app_namespace }}"
    api_version: v1
    kind: Namespace
    state: present

# El secreto que será creado es para que se pueda hacer pull de las imágenes almacenas en el ACR
- name: Creando secreto para acceso al ACR...
  kubernetes.core.k8s:
    definition: "{{ lookup('template', 'acr_secrets.yml.j2') }}"
    state: present

# PVC es un espacio persistente (Volumen) para que los datos no desaparezcan en caso de reinicio o eliminación del pod
- name: Creando PersistentVolumeClaim...
  kubernetes.core.k8s:
    definition: "{{ lookup('template', 'persistentvolumeclaim.yml.j2') }}"
    state: present

# Despliegue del servicio backend usando un template almacenado en el directorio templates
- name: Desplegando backend...
  kubernetes.core.k8s:
    definition: "{{ lookup('template', 'backend.yml.j2') }}"
    state: present

# Despliegue del servicio frontend usando un template almacenado en el directorio templates
- name: Desplegando frontend...
  kubernetes.core.k8s:
    definition: "{{ lookup('template', 'frontend.yml.j2') }}"
    state: present