---
# Aquí se declaran las variables que usaremos para la creación
# de todos los servicios en el rol de vm

app_name: "nginx"
tag_imagen: "casopractico2"
nginx_port_host: 8086
nginx_port_container: 80
nginx_ssl_port_host: 443
nginx_ssl_port_container: 443
nginx_volume_appdata: "/opt/appdata"
nginx_volume_parent: "/opt/nginx"
nginx_volume_ssl: "/opt/nginx/ssl"
nginx_volume_conf: "/opt/nginx/conf"
nginx_ca_cert: "ca.crt"
nginx_ca_key: "ca.key"
nginx_ca_csr: "ca.csr"
key_size: "2048"
ca_common_name: "CP2-CA"
ca_organization_name: "UNIR"
ca_country_name: "ES"
ca_basic_constraints: "CA:TRUE"
cert_selfsigned_digest: "sha256"
cert_selfsigned_not_after: "+36500d"
cert_selfsigned_not_before: "+0s"
nginx_cert_crt: "nginx.crt"
nginx_cert_key: "nginx.key"
nginx_cert_csr: "nginx.csr"
OrganizationNameCert: "UNIR"
nginx_template_config: "nginx.conf.j2"
nginx_destination_config: "nginx.conf"
web_index_template: "index.html"
web_index_destination: "index.html"