#!/bin/bash

# ------------------------------------------------------------------------------
# Script: start
# Autor: Óscar Nappo
# Fecha de creación: 01/03/2026
# Proyecto: Despliegue de Infraestructura en Azure con Terraform y Ansible
# Versión: 1.4
# Fecha última modificación: 13/03/2026
# Descripción:
#   Este script muestra un menú interactivo para gestionar el despliegue
#   de la infraestructura en Azure.
# ------------------------------------------------------------------------------

######################################
### BLOQUE DE FUNCIONES AUXILIARES ###
######################################

# Muestra un menú interactivo
show_menu() {
    echo "+--------------------------------------------------+"
    echo "+  ¡Bienvenid@ al menú interactivo del CP2!        +"
    echo "+                                                  +"
    echo "+    Elija una de las siguientes opciones:         +"
    echo "+--------------------------------------------------+"
    echo "+                                                  +"
    echo "+   0. Salir                                       +"
    echo "+   1. Instalar Dependencias                       +"
    echo "+   2. Iniciar Despliegue                          +"
    echo "+   3. Destruir Infraestructura                    +"
    echo "+                                                  +"
    echo "+--------------------------------------------------+"
    echo ""
    read -rp "Selecciona una opcion [0-3]: " option
}

show_deploy_menu() {
    echo "+--------------------------------------------------+"
    echo "+   Seleccione qué quiere desplegar:               +"
    echo "+--------------------------------------------------+"
    echo "+                                                  +"
    echo "+   0. Retroceder al Menú Principal                +"
    echo "+   1. Desplegar Infraestructura [Terraform]       +"
    echo "+   2. Desplegar Servicios [Ansible]               +"
    echo "+   3. Desplegar Todo [Terraform + Ansible]        +"
    echo "+                                                  +"
    echo "+--------------------------------------------------+"
    echo ""
    read -rp "Selecciona una opcion [0-3]: " deploy_option
}


# Setea las variables de entorno
set_vars(){
    # Carga las variables de entorno
    SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
    source "$SCRIPT_DIR/config"
    
    # Directorio raiz del Script 
    SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
    ROOT_DIR="$(dirname "$SCRIPT_DIR")"
}

# Realiza un backup del fichero de variables de terraform
backup_file(){
    cp "$TF_VARS_FILE" "${TF_VARS_FILE}.template"
}

# Configura el ID de Azure para lanzar peticiones a la API
set_azid(){
    AZ_SUBS_ID=$(az account show --query "id" -o tsv)
    sed -i "s|AZ_SUBS_ID|$AZ_SUBS_ID|g" "$TF_VARS_FILE"
}

# Destruye la intraestructura completa
destroy_infra(){
    local approve_flag="${1:-}"

    if ! terraform -chdir=$TF_DIR destroy $approve_flag; then
        echo "Error al destruir los recursos. Revise los errores indicados más arriba."
    fi
}

# Recupera el fichero de variables por defecto de terraform
rollback_config_files() {
    if [ -f "${TF_VARS_FILE}.template" ]; then
        mv "${TF_VARS_FILE}.template" "$TF_VARS_FILE"
        echo "Archivo de variables de Terraform restaurado a su estado original."
    fi
}

######################
### BLOQUE DE MENÚ ###
######################

while true; do
    show_menu
    case $option in
        0)
            echo ""
            echo "Saliendo..."
            if declare -f unset_sensitive_variables > /dev/null; then
                unset_sensitive_variables
            fi
            exit 0
            ;;
        1)
            echo ""
            echo "Instalando dependencias..."
            set_vars
            bash "$SCRIPT_DIR/setup"
            read -rp "Pulsa Enter para continuar..."
            ;;
        2)
            while true; do
                show_deploy_menu
                case $deploy_option in
                    0)
                        echo ""
                        echo "Retrocediendo al menú principal..."
                        break
                        ;;
                    1)
                        echo ""
                        echo "Desplegando estructura con Terraform..."
                        set_vars
                        while true; do
                            read -rp "¿Aplicar cambios sin confirmación? [s/n]: " confirm
                            if [[ "$confirm" == "s" ]]; then
                                bash "$SCRIPT_DIR/deploy" terraform auto-approve
                                break
                            elif [[ "$confirm" == "n" ]]; then
                                bash "$SCRIPT_DIR/deploy" terraform
                                break
                            else
                                echo "Opción no válida. Por favor, introduce 's' o 'n'."
                            fi
                        done
                        read -rp "Pulsa Enter para continuar..."
                        break
                        ;;
                    2)
                        # Desplegaremos con Ansible solo si se ha hecho previamente con Terraform.
                        # Esto se comprueba en deploy
                        echo ""
                        echo "Desplegando servicios con Ansible..."
                        set_vars
                        bash "$SCRIPT_DIR/deploy" ansible
                        read -rp "Pulsa Enter para continuar..."
                        break
                        ;;
                    3)
                        echo ""
                        echo "Desplegando infraestructura y servicios Terraform + Ansible..."
                        set_vars
                        while true; do
                            read -rp "¿Aplicar cambios sin confirmación? [s/n]: " confirm
                            if [[ "$confirm" == "s" ]]; then
                                bash "$SCRIPT_DIR/deploy" all auto-approve
                                break
                            elif [[ "$confirm" == "n" ]]; then
                                bash "$SCRIPT_DIR/deploy" all
                                break
                            else
                                echo "Opción no válida. Por favor, introduce 's' o 'n'."
                            fi
                        done
                        read -rp "Pulsa Enter para continuar..."
                        break
                        ;;
                    *)
                        echo ""
                        echo "Opcion no valida. Por favor, selecciona una opcion entre 0 y 2."
                        read -rp "Pulsa Enter para continuar..."
                        ;;
                esac
            done
            ;;
        3)
            echo ""
            echo "Destruyendo infraestructura..."
            set_vars
            backup_file
            set_azid
            while true; do
            read -rp "¿Aplicar cambios sin confirmación? [s/n]: " confirm
                if [[ "$confirm" == "s" ]]; then
                    destroy_infra "-auto-approve"
                    break
                elif [[ "$confirm" == "n" ]]; then
                    destroy_infra
                    break
                else
                    echo "Opción no válida. Por favor, introduce 's' o 'n'."
                fi
            done
            rollback_config_files
            read -rp "Pulsa Enter para continuar..."
            ;;
        *)
            echo ""
            echo "Opcion no valida. Por favor, selecciona una opcion entre 1 y 3."
            read -rp "Pulsa Enter para continuar..."
            clear
            ;;
    esac
done
